name: Terraform check
on:
  workflow_dispatch:
  push:
    paths:
      - '**.tf'

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
    uses: random-builds/gh-workflows/.github/workflows/terraform-check.yaml@fa822e940db0de772a79ace0e5aa0a7205681eab
    with:
      terraform_version: 1.11.4
